In [1]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
X_train = np.array([[1,1,1],[1,0,1],[1,0,0],[1,0,0],[1,1,1],[0,1,1],[0,0,0],[1,0,1],[0,1,0],[1,0,0]])
y_train = np.array([1,1,0,0,1,0,0,1,1,0])

In [32]:
def compute_entropy(y):
    probPos = np.sum(y)/len(y)
    if probPos == 0 or probPos == 1 or len(y) == 0:
        return 0
    return -probPos*np.log2(probPos) - (1 - probPos)*np.log2((1 - probPos))

In [31]:
def split_feature(X, node_indices, feature):
    node_features = X[node_indices]
    node_indices = np.asarray(node_indices)
    left_split = node_indices[np.where(node_features[:, feature] == 0)[0]]
    right_split = node_indices[np.where(node_features[:, feature] == 1)[0]]
    return left_split, right_split

In [37]:
def compute_information_gain(X, y, left_indices, right_indices):
    node_indices = np.concatenate((left_indices, right_indices))
    node_features, node_classes = X[node_indices], y[node_indices]
    left_classes, right_classes = y[left_indices], y[right_indices]

    base_entropy = compute_entropy(node_classes)
    left_entropy, right_entropy = compute_entropy(left_classes), compute_entropy(right_classes)

    weighted_entropy = (len(left_classes)/len(node_classes) * left_entropy) + (len(right_classes)/len(node_classes) * right_entropy)
    return base_entropy - weighted_entropy


In [38]:
left_indices_test, right_indices_test = split_feature(X_train, range(9), 0)
compute_information_gain(X_train, y_train, left_indices_test, right_indices_test)

0.07278022578373267

In [30]:
split_feature(X_train, [0, 1, 3, 5], 0)

[[1 1 1]
 [1 0 1]
 [1 0 0]
 [0 1 1]]


(array([5]), array([0, 1, 3]))